### ISSUE TITLE
how do I use llvm-msvc after compiling it?

### ISSUE THREAD

**Issue by chiefmasterR** [backengineering/llvm-msvc#105]
I compiled the llvm-msvc from source and have no idea what should I do next, how do I make "LLVM-MSVC_v143_KernelMode" toolset appear in the visual studio?

**Comment by CR3Swapper** [comment]
https://github.com/backengineering/llvm-msvc-installer-src

You can use this repo to build an installer for your compiled version of llvm-msvc. Also if you want you can use pre-compiled version of llvm-msvc.
