### ISSUE TITLE
777.18 build crash

### ISSUE THREAD

**Issue by ccdescipline** [backengineering/llvm-msvc#107]
我卸载老版本安装新版本后编译报错
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6006: “C:\Users\admin\Downloads\llvm-msvc_X86_64\bin\clang-cl.exe”已退出，代码为 -1073741819。

**Comment by je5442804** [comment]
### 崩溃函数 msvcp140.dll!mtx_do_lock  
由 C++的 std::mutex::lock() 调用，该问题不仅仅在LLVM, Clang上出现.  

### 解决方案:  
1: 升级 VC 运行时到 2024.06++(2024.07++/2024.08++)  
2: 临时复制Edge或者其他应用的最新msvcp140.dll到clang-cl.exe的目录下（注意x86 or x64)  
例如 C:\Program Files (x86)\Microsoft\EdgeCore\127.0.2651.105\msvcp140.dll (x64)  

### 根本原因归功于 **微软  o.0  
https://stackoverflow.com/questions/78598141/first-stdmutexlock-crashes-in-application-built-with-latest-visual-studio  
https://github.com/actions/runner-images/issues/10004  
https://github.com/actions/runner-images/issues/10020

**Comment by gmh5225** [comment]
根本原因归功于 **微软 o.0
