### ISSUE TITLE
编译7z的报错

### ISSUE THREAD

**Issue by killvxk** [backengineering/llvm-msvc#19]
`  #if defined(__clang__) && (__clang_major__ >= 8) \
    || defined(__GNUC__) && (__GNUC__ >= 8) \
    || defined(__INTEL_COMPILER) && (__INTEL_COMPILER >= 1900)
      #define USE_SATUR_SUB_128
      #define USE_AVX2
`
很明显你的莫名其妙的不支持USE AVX2

**Comment by gmh5225** [comment]
已支持https://github.com/backengineering/llvm-msvc/commit/af4c0cbf06be387949457f3941b1d886372f2add
