### ISSUE TITLE
How to overwrite with LLVM from VS Installer?

### ISSUE THREAD

**Issue by bphucc** [backengineering/llvm-msvc#41]
I've installed LLVM and Clang from VS Installer, as this image below:
![image](https://github.com/backengineering/llvm-msvc/assets/42881433/1443a673-faed-46b7-8db5-c1121bcd76e8)
Now I want to overwrite this llvm-msvc project with that LLVM version. I tried to go to `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\Llvm` but it turns out that the structure of that original folder differ from this project (I compiled myself):
![image](https://github.com/backengineering/llvm-msvc/assets/42881433/7418355e-c04e-431b-a74b-be18241811e2)

So my question is how to use this project as the custom compiler integrated into Visual Studio 2019? My version also add obfuscation. I read [here](https://www.unknowncheats.me/forum/anti-cheat-bypass/500042-ollvm-13-llvm-obfuscator-vs2022.html) as well as [here](https://www.unknowncheats.me/forum/anti-cheat-bypass/445826-llvm-obfuscator-9-0-1-step-step-visual-studio.html) that they said I must replace the original folder with a new one?

**Comment by gmh5225** [comment]
The project is not yet complete and there is no mature documentation.
You can take a look at some of the instructions I wrote [before](https://github.com/NewWorldComingSoon/llvm-msvc-build)

**Comment by bphucc** [comment]
After searching for a while, I found out that you can add a custom LLVM version into Visual Studio by following [this tutorial](https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170#custom_llvm_location), then you can use it normally as the original one of VS.

**Comment by gmh5225** [comment]
Very strong.  👍
