### ISSUE TITLE
/GR with /kernel

### ISSUE THREAD

**Issue by ld1856** [backengineering/llvm-msvc#52]
use memory c++ in kernel mode driver
/gr could not use in /kernel 
so all the headers would throw an error like
"error : use of typeid requires -frtti" within compilling

**Comment by gmh5225** [comment]
Could you provide a demo project?

**Comment by ld1856** [comment]
just test with https://github.com/tandasat/HyperPlatform

**Comment by gmh5225** [comment]
The key is not ``/GR``. MSVC also reports an error.
``cl : command line  error D8016: '/GR' and '/kernel' command-line options are incompatible``

I fixed the compilation problem of [HyperPlatform](https://github.com/build-testing/HyperPlatform) on version [3.2.1](
https://github.com/backengineering/llvm-msvc/releases/tag/llvm-msvc-v3.2.1)

**Comment by ld1856** [comment]
When I compile HyperPlatform using vs2019+llvm-msvc-3.2.1+sdk10.0.19041.0, it prompts "error : ISO C++17 does not allow dynamic exception specifications [-Wdynamic-exception-spec]".

**Comment by gmh5225** [comment]
Thanks for reporting the bug, I'll try to fix it for ``VS2019``.
I recommend you to use ``VS2022`` or change C++ language to ``ISO C++14 Standard (/std:c++14)``.

**Comment by ld1856** [comment]
> Thanks for reporting the bug, I'll try to fix it for `VS2019`. I recommend you to use `VS2022` or change C++ language to `ISO C++14 Standard (/std:c++14)`.


this my code:
```cpp
template <class _Dx>
auto test()
{
	return typeid(_Dx);
}
```

**Comment by gmh5225** [comment]
> Thanks for reporting the bug, I'll try to fix it for `VS2019`. I recommend you to use `VS2022` or change C++ language to `ISO C++14 Standard (/std:c++14)`.

You can try [v3.2.3](https://github.com/backengineering/llvm-msvc/releases/tag/llvm-msvc-v3.2.3)
