### ISSUE TITLE
x86 support?

### ISSUE THREAD

**Issue by ghost** [backengineering/llvm-msvc#56]
The Readme only mentions the 64-bit drivers, how good or bad is the x86 support?

**Comment by gmh5225** [comment]
I haven't tested it on the X86-32 system yet, but it should work in theory. If you run into any issues, just let me know.

**Comment by ghost** [comment]
So far the issues i had turned out to be mistakes in the code which didn't cause problems with MSVC. Fixing these made me miss Edit and Continue.

**Comment by gmh5225** [comment]
If you run into issues. You can provide a demo project. We'll see.

**Comment by ghost** [comment]
In case i encounter a programming issue in my code that msvc doesn't care about but clang does is that even in the scope of this fork? I would think i should fix it on my side.

**Comment by gmh5225** [comment]
Let me see your code.

**Comment by ghost** [comment]
I'am compiling a dll for a Civilization IV  modding project which is using the msvc 7.1 runtime. The `_vsnprintf` function from that ancient runtime behaves differently with clang when the arguments don't match the format specifier. Like mixing `char` and `wchar` when using `%s`.

**Comment by gmh5225** [comment]
Got it. In this case. I suggest you make changes to the code.

**Comment by ghost** [comment]
Overall the compatability even with vanilla clang is surprisingly good. It's easier to use clang to compile against the 7.1 runtime as using a up to date msvc compiler is. The msvc compiler relies heavily on the runtime which makes this a challenge. However this depends on things like code quality because in some cases msvc is more tolerant.

**Comment by gmh5225** [comment]
Agreed, if you have any other issues, feel free to give us feedback.
