### ISSUE TITLE
 lld-link error when compilation  driver

### ISSUE THREAD

**Issue by pythonfansx** [backengineering/llvm-msvc#62]
Error occurred during the driver compilation process: lld-link: error: /INCREMENTAL:NO is not allowed in .drectve (x64\Debug\khookutil.obj), llvm-msvc is the latest. How to solve such an error?

**Comment by pythonfansx** [comment]
<img width="613" alt="image" src="https://github.com/backengineering/llvm-msvc/assets/34299978/4146df0a-66f0-479d-8164-47ecb3c0c69b">

**Comment by gmh5225** [comment]
Try this [temporary version](https://github.com/backengineering/llvm-msvc/suites/19036279525/artifacts/1114260595), I think it has solved your issues. 
If it works for you, please tell me, thanks.

**Comment by pythonfansx** [comment]
> Try this [temporary version](https://github.com/backengineering/llvm-msvc/suites/19036279525/artifacts/1114260595), I think it has solved your issues. If it works for you, please tell me, thanks.

ok  I found that the above-mentioned issue has been fixed after testing. As my code has been ported, there are still some other errors, but I believe they are not closely related to lld-link. Thank you very much for your assistance
