### ISSUE TITLE
May I ask how to use llvm-msvc-windows.zip?

### ISSUE THREAD

**Issue by yaoguen** [backengineering/llvm-msvc#73]
May I ask how to use llvm-msvc-windows.zip?

**Comment by gmh5225** [comment]
## How to use llvm-msvc?
- Install Visual Studio 2015 to 2022 (I recommend using 2022) along with WDK11.
- Download and install llvm-msvc from the following repository ([llvm-msvc_X86_64_installer.exe](https://github.com/backengineering/llvm-msvc/releases))
- Create your Windows driver project and choose "LLVM-MSVC_v143_KernelMode" as your platform toolset.
- Compile your project.

**Comment by yaoguen** [comment]
I have installed llvm-msvc_X86_64_installer.exe，But I didn't find right how to use the file llvm-msvc-windows.zip。

**Comment by gmh5225** [comment]
llvm-msvc-windows.zip just contains the complete compilation result.

**Comment by yaoguen** [comment]
Thank you very much.
