### ISSUE TITLE
MSVC pre-define macros

### ISSUE THREAD

**Issue by CR3Swapper** [backengineering/llvm-msvc#77]
does llvm-msvc (or clang-cl) offer microsofts pre-defined compiler definitions? 

https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170&redirectedfrom=MSDN

Just wondering!

**Comment by gmh5225** [comment]
I'm not sure. we need some testings.

**Comment by gmh5225** [comment]
It works well 
https://github.com/build-testing/Predefined-macro-testing
