### ISSUE TITLE
about obfuscation

### ISSUE THREAD

**Issue by ccdescipline** [backengineering/llvm-msvc#8]
I want to know how to obfuscation

**Comment by gmh5225** [comment]
For the time being, there is no plan to release obfuscation related things within 1 year.
You need to port OLLVM yourself 👍

**Comment by hzqst** [comment]
Check the following repos:

https://github.com/AimiP02/BronyaObfus
https://github.com/wwh1004/ollvm-16
https://github.com/KomiMoe/Arkari
https://github.com/bluesadi/Pluto-Obfuscator

**Comment by killvxk** [comment]
just make one fork for ollvm
https://github.com/killvxk/llvm-msvc-ex

**Comment by cloudhoter** [comment]
> just make one fork for ollvm https://github.com/killvxk/llvm-msvc-ex

I downloaded your source code, but the build failed, and so did I for another computer. There were 20 errors
Could you upload Release?

**Comment by killvxk** [comment]
> > just make one fork for ollvm https://github.com/killvxk/llvm-msvc-ex
> 
> I downloaded your source code, but the build failed, and so did I for another computer. There were 20 errors Could you upload Release?

https://github.com/killvxk/llvm-msvc-ex/releases/tag/x64

**Comment by CR3Swapper** [comment]
moving this topic here: https://github.com/backengineering/llvm-msvc/discussions/55
